# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
# cache: cocoapods
before_install:
- gem install cocoapods # Since Travis is not always on latest version
script:
- carthage build --platform ios,tvos
- fastlane scan --scheme Framework-iOS
- fastlane scan --scheme Framework-tvOS
- pod lib lint
